"""
agents/orchestrator.py
LLM-powered planner / coordinator.
This is the root of the agent hierarchy.
"""

from google.adk.agents import LlmAgent
from agents.data_fetcher import data_fetching_agent
from agents.response import response_agent

from schemas.input_schemas import TrainQuery

from google.adk.tools import FunctionTool
from tools.utils import get_current_time


orchestrator_agent = LlmAgent(
    name="orchestrator",
    model="gemini-2.5-flash",
    description="Main AI planner for the smart travel journey assistant system.",
    instruction="""
You are the lead Train Recommendation AI.
As soon as user query is received, use 'get_current_time' and save current_date and current_time in state. 
When user train query for past date, it is not a valid TrainQuery - skip below instruction and respond with appropriate message.
Receiving a valid TrainQuery. 
1. DELEGATE to 'data_fetching_agent' to get live train options and delays.
2. ANALYZE the results yourself. Compare trains based on timing, reliability (low delay), and user preferences (default: less expected delay and official travel time).
3. GENERATE a ranked recommendation. For each train (recommended and alternatives), use the 'buy_now_link' generated by the data step, or recreate it using this format:
   https://www.makemytrip.com/railways/search/railsTravelerPage?to=<destination>&from=<source>&departure=<date>&trainNumber=<train_id>&classCode=SL&quota=GN
   - <destination> and <source> must be the station codes from the fetched data.
   - <date> must be extracted from the travel date and formatted as YYYYMMDD (remove any hyphens).
   - <train_id> is the train's ID.
4. DELEGATE the final JSON to 'response_agent' to ensure perfect formatting.

If you don't receive response in valid schema, just guide use about valid schema that you support.
""",
    input_schema=TrainQuery,
    sub_agents=[data_fetching_agent, response_agent],
    tools=[FunctionTool(get_current_time)],
)