"""
Productivity agent — single-user mode using workspace-mcp --single-user.

Architecture
------------
workspace-mcp runs as a stdio subprocess with --single-user flag.
Credentials for USER_GOOGLE_EMAIL are pre-baked into the Docker image
by copying credentials/<email>.json (generated by setup_credentials.py).

On Cloud Run:
  /root/.google_workspace_mcp/credentials/<email>.json  ← copied at build
  workspace-mcp --single-user  ← reads this file directly, no browser needed
"""

from __future__ import annotations

import logging
import os

from dotenv import load_dotenv
from google.adk.agents import LlmAgent
from agents.base import PatchedMcpToolset
from google.adk.tools.mcp_tool.mcp_session_manager import StdioConnectionParams
from mcp import StdioServerParameters

load_dotenv()
logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

USER_GOOGLE_EMAIL = os.getenv("USER_GOOGLE_EMAIL", "")

_raw_args = os.getenv("WORKSPACE_MCP_ARGS", "--single-user --tool-tier extended")
# Normalise: ensure --single-user is present, strip any invalid flags
_args_list = [a for a in _raw_args.split() if a != "--multi-user"]
if "--single-user" not in _args_list:
    _args_list.insert(0, "--single-user")
WORKSPACE_MCP_ARGS = _args_list


# ---------------------------------------------------------------------------
# Binary detection (cross-platform)
# ---------------------------------------------------------------------------

def _find_mcp_executable() -> str:
    """Return the path to the workspace-mcp binary."""
    base = os.path.dirname(os.path.dirname(__file__))
    candidates = [
        os.path.join(base, "venv", "Scripts", "workspace-mcp.exe"),  # Windows dev
        os.path.join(base, "venv", "bin",     "workspace-mcp"),       # Linux dev venv
        "/usr/local/bin/workspace-mcp",                                # Docker pip install
        "/app/venv/bin/workspace-mcp",                                 # Docker /app workdir
    ]
    for path in candidates:
        if os.path.exists(path):
            logger.info("workspace-mcp binary: %s", path)
            return path
    cmd = os.getenv("WORKSPACE_MCP_COMMAND", "workspace-mcp")
    logger.info("workspace-mcp not found in known paths — using: %s", cmd)
    return cmd


MCP_EXECUTABLE = _find_mcp_executable()


# ---------------------------------------------------------------------------
# Agent factory
# ---------------------------------------------------------------------------

def get_productivity_agent(user_email: str = "", access_token: str = "") -> LlmAgent:
    """
    Builds a fresh LlmAgent scoped to the configured single user.

    Parameters
    ----------
    user_email:
        The Google email to use. Falls back to USER_GOOGLE_EMAIL from .env.
    access_token:
        Optional OAuth2 access token for bearer authentication.
    """
    if not user_email:
        user_email = USER_GOOGLE_EMAIL
    if not user_email:
        user_email = "me"

    _instruction = f"""\
You are a productivity assistant for a train travel booking system.

You will receive a JSON object describing a confirmed train recommendation.
Your job is to execute exactly THREE actions using your tools — no more, no less.

The user's Google account email is: {user_email}
Use this email as user_google_email in every tool call.

============================================================
STEP 1 — Google Tasks (manage_task)
============================================================
Create a reminder task with these exact parameters:

    action            = "create"
    user_google_email = "{user_email}"
    task_list_id      = "@default"

    title = "Book cab to <source> station"

    due = RFC3339 timestamp computed as:
        Logic: travel_date + departure_time minus 2 hours
        Timestamp Format: YYYY-MM-DDTHH:MM:SSZ
        Example:
            travel_date="2026-04-17"
            departure_time="06:45"
            → due="2026-04-17T04:45:00Z"

    notes = "Train Live: https://www.makemytrip.com/railways/railStatus/?q1=<train_id>&q3=<YYYY-MM-DD>"

============================================================
STEP 2 — Google Calendar (manage_event)
============================================================
Create a calendar event with these exact parameters:

    action              = "create"
    user_google_email   = "{user_email}"
    calendar_id         = "primary"

    summary             = "<train_id> | <train_name> | <source> → <destination>"

    start_time          = "<date>T<departure_time>:00" (RFC3339 Format: YYYY-MM-DDTHH:MM:SSZ)
    end_time            = "<date>T<arrival_time>:00"   (add 1 day if arrival < departure)

    description         = \"\"\"Train Journey

📍 Route: <source> → <destination>
🚂 Train: <train_name> (<train_id>)
📅 Date: <travel_date>
⏰ Departure: <departure_time>  |  Arrival: <arrival_time>

🔴 Live Status: https://www.makemytrip.com/railways/railStatus/?q1=<train_id>&q3=<YYYY-MM-DD>
🍽 Order Food: https://www.railrestro.com/trains/<train_name with + instead of space>?DOJ=<DDMMYYYY>

✅ Booked via Smart Travel Journey Planner
\"\"\"

    location            = "<source> Railway Station"

============================================================
STEP 3 — Gmail Draft (draft_gmail_message)
============================================================
Create a Gmail draft with these exact parameters:

    user_google_email = "{user_email}"
    to                = "{user_email}"
    subject           = "Journey Reminder: <train_name> on <date>"

    body = \"\"\"Hi,

This is a reminder for your upcoming train journey:

🚂 Train:     <train_name> (<train_id>)
📍 Route:     <source> → <destination>
📅 Date:      <travel_date>
⏰ Departure: <departure_time>
🏁 Arrival:   <arrival_time>

🔴 Live Status:  https://www.makemytrip.com/railways/railStatus/?q1=<train_id>&q3=<YYYY-MM-DD>
🍽 Order Food:   https://www.railrestro.com/trains/<train_name with + instead of space>?DOJ=<DDMMYYYY>

Have a safe journey!
\"\"\"

============================================================
RULES
============================================================

1. Execute ALL THREE steps even if one fails.
2. Do NOT skip any step.
3. Do NOT write Python. Do NOT explain — just call the tools.
4. After all three calls complete, write a brief summary of what was done.
"""

    connection_params = StdioConnectionParams(
        server_params=StdioServerParameters(
            command=MCP_EXECUTABLE,
            args=WORKSPACE_MCP_ARGS,
            env=os.environ.copy(),
        ),
        timeout=90.0,
    )

    return LlmAgent(
        name="productivity_agent",
        model="gemini-2.5-flash",
        description=(
            "Creates a Google Task, Calendar event, and drafts a Gmail reminder "
            "for a confirmed train booking."
        ),
        instruction=_instruction,
        tools=[
            PatchedMcpToolset(
                connection_params=connection_params,
                auth_credential=access_token if access_token else None
            )
        ],
    )


# ---------------------------------------------------------------------------
# Module-level instance for ADK web / adk run / orchestrator compatibility
# ---------------------------------------------------------------------------
productivity_agent = get_productivity_agent()
